on:
  push:
    branches:
      - main
      - master
      - tmp-test-windows-toolchain
  pull_request:
    branches:
      - main
      - master

name: Test package generation

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }} / ${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rust-version: 'stable-msvc'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - name: Configure Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          Remove-Item $env:GITHUB_PATH
          echo "C:\R\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append 
          echo "C:\rtools40\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Rust\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: echo
        if: startsWith(runner.os, 'Windows')
        run: |
          echo $env:PATH
        shell: pwsh