on:
  push:
    branches:
      - main
      - master
      - tmp-test-windows-toolchain
  pull_request:
    branches:
      - main
      - master

name: Test package generation

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }} / ${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rust-version: 'stable-msvc'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.rust-version }}
          default: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          windows-path-include-mingw: false

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages (not Windows)
        if: startsWith(runner.os, 'Windows') == false
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Configure Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-pc-windows-gnu
          Remove-Item -Recurse C:\msys64
        shell: pwsh

      - name: Configure Linux
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo apt-get install libcurl4-openssl-dev
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')


      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("devtools")
          remotes::install_cran("usethis")
        shell: Rscript {0}

      - name: Test package generation
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          # preperation
          remotes::install_local(force = TRUE)
          temp_dir <- tempdir()
          pkg_dir <- file.path(temp_dir, "testpkg")
          dir.create(pkg_dir, recursive = TRUE)
          setwd(pkg_dir)
          Sys.setenv(REXTENDR_TEST_PKG_ROOT = getwd())
          devtools::create(".")
          usethis::proj_activate(".")
          rextendr::use_extendr()
          usethis::use_mit_license()
          usethis::use_testthat()
          brio::write_lines(
            c(
              "test_that(\"`hello_world()` works\", {",
              "  expect_equal(hello_world(), \"Hello world!\")",
              "})",
              "test_that(\"`rextendr::use_extendr()` works\", {",
              "  wrap_path <- file.path(Sys.getenv(\"REXTENDR_TEST_PKG_ROOT\"), \"R\", \"extendr-wrappers.R\")",
              "  expect_equal(readLines(wrap_path, 1), \"# Generated by extendr: Do not edit by hand\")",
              "})"
            ),
            file.path("tests", "testthat", "test-hello.R")
          )

          # check if rextendr::document() compiles and generates wrappers properly
          rextendr::document()
          rcmdcheck::rcmdcheck(
              path = ".",
              args = c("--no-manual", "--as-cran"),
              error_on = "warning",
              check_dir = "check_use_extendr"
          )

          library_path <- rextendr:::get_library_path()
          library_mtime_before <- file.info(library_path)$mtime
          wrappers_path <- file.path("R", "extendr-wrappers.R")
          wrappers_mtime_before <- file.info(wrappers_path)$mtime

          # check if rextendr::document() don't re-generate wrappers when unnecessary
          rextendr::document()
          stopifnot(library_mtime_before == file.info(library_path)$mtime)
          stopifnot(wrappers_mtime_before == file.info(wrappers_path)$mtime)

          # check if force = TRUE forces re-generating wrappers, but not compile
          rextendr::register_extendr(force = TRUE)
          stopifnot(library_mtime_before == file.info(library_path)$mtime)
          stopifnot(wrappers_mtime_before < file.info(wrappers_path)$mtime)

          wrappers_mtime_before <- file.info(wrappers_path)$mtime

          # check if compile = TRUE forces compile, and accordingly the wrapper generation
          rextendr::register_extendr(compile = TRUE)
          stopifnot(library_mtime_before < file.info(library_path)$mtime)
          stopifnot(wrappers_mtime_before < file.info(wrappers_path)$mtime)
        shell: Rscript {0}
